# Generated by Django 2.0.8 on 2018-10-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcd',
            name='profissão',
            field=models.CharField(choices=[('0', 'Vagabundo'), ('1', 'Outro')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcd',
            name='sexo',
            field=models.CharField(choices=[('0', 'Feminino'), ('1', 'Masculino')], default=' ', max_length=1),
            preserve_default=False,
        ),
    ]
